version: '3.8'
services:
  sqlboiler_notion_sample_db:
    build:
      context: docker/db
    image: sqlboiler_notion_sample_db
    container_name: sqlboiler_notion_sample_db
    ports:
      - 10001:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample

  sqlboiler_notion_sample_go:
    build:
      context: docker/go
    image: sqlboiler_notion_sample_go
    container_name: sqlboiler_notion_sample_go
    volumes:
      - $PWD:/workspace
    environment:
      DB_HOST: sqlboiler_notion_sample_db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      DB_NAME: sample

volumes:
  mysql:
